services:
  cajoncito-backend:
    container_name: cajoncito-backend
    build:
      # Aquí sucede la magia: Docker clona el repo por ti
      context: https://github.com/tu-usuario/cajoncito-backend.git#main
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      # Agrega aquí tus variables de entorno necesarias
    restart: always
