services:
  cajoncito-backend:
    container_name: cajoncito-backend
    build:
      # Aqu√≠ sucede la magia: Docker clona el repo por ti
      context: https://github.com/carlosgnx/cajoncito-backend.git#main
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always
